### ISSUE TITLE
EpollWait: Should this check for -1 and loop?

### ISSUE THREAD

**Issue by kardianos** [davecheney/gpio#12]
I recently got the following panic:
panic: EpollWait error: interrupted system call

goroutine 3 [running]:
github.com/davecheney/gpio.func·001()
        /home/pi/code/src/github.com/davecheney/gpio/gpio_linux.go:74 +0x1d4
created by github.com/davecheney/gpio.setupEpoll
        /home/pi/code/src/github.com/davecheney/gpio/gpio_linux.go:87 +0x1d8

This is on a rpi.
It would seem that epoll should loop here if the err is a -1. Does this sound about right? Only reason I saw this was it was in an nohup.out log, normally runs fine.

**Comment by isaiasma** [comment]
Hi,

I think "interrupted system call" is not syscall.EAGAIN, 'interrupted system call' is syscall.EINTR

```c
/usr/include/asm/errno.h
#define EAGAIN          11      /* Try again */
#define EINTR            4      /* Interrupted system call */
```
[Stackoverflow how to handle interrupted system call](http://stackoverflow.com/questions/1674162/how-to-handle-eintr-interrupted-system-call)
